# Generated by Django 4.2.8 on 2024-01-08 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='translate',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='word',
            name='word',
            field=models.CharField(max_length=50),
        ),
    ]
