# Generated by Django 4.2.8 on 2024-01-09 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mydictionaryapp', '0002_alter_word_translate_alter_word_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_key', models.CharField(max_length=64)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydictionaryapp.word')),
            ],
        ),
    ]
